# Generated by Django 5.2.10 on 2026-04-20 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_adminsetting_analytics_dashboard_inventoryscan_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AdminSetting",
        ),
        migrations.DeleteModel(
            name="Analytics",
        ),
        migrations.RemoveField(
            model_name="inventoryscan",
            name="scanned_by",
        ),
        migrations.RemoveField(
            model_name="inventoryscan",
            name="upload",
        ),
        migrations.RemoveField(
            model_name="loginactivity",
            name="user",
        ),
        migrations.RemoveField(
            model_name="result",
            name="upload",
        ),
        migrations.RemoveField(
            model_name="upload",
            name="user",
        ),
        migrations.RemoveField(
            model_name="usersetting",
            name="user",
        ),
        migrations.DeleteModel(
            name="Dashboard",
        ),
        migrations.DeleteModel(
            name="InventoryScan",
        ),
        migrations.DeleteModel(
            name="LoginActivity",
        ),
        migrations.DeleteModel(
            name="Result",
        ),
        migrations.DeleteModel(
            name="Upload",
        ),
        migrations.DeleteModel(
            name="UserSetting",
        ),
    ]
