# Generated by Django 5.2.10 on 2026-04-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Analytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("total_uploads", models.PositiveIntegerField(default=0)),
                ("successful_scans", models.PositiveIntegerField(default=0)),
                ("failed_scans", models.PositiveIntegerField(default=0)),
                ("avg_processing_time_ms", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-period_end"],
            },
        ),
    ]
